version: '3.9'
name: grimoire_stack

services:
    grimoire:
        image: ghcr.io/yucked/grimoire:latest
        container_name: grimoire
        restart: unless-stopped
        ports:
            - 9000:9000
            - 9001:9001
        networks:
            - net-grim
        volumes:
            - ./data/grimoire:/app/out/Grimoire_Data
            - ./data/config.json:/app/out/config.json
        deploy:
            resources:
                limits:
                    memory: 2G

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        networks:
            - net-grim
        environment:
            MONGO_INITDB_ROOT_USERNAME: grimoire
            MONGO_INITDB_ROOT_PASSWORD: grimoire
        volumes:
            - ./data/mongo:/data/db
    
    mongo-express:
        image: mongo-express
        container_name: mongo_express
        restart: always
        ports:
            - 8081:8081
        networks:
            - net-grim
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: grimoire
            ME_CONFIG_MONGODB_ADMINPASSWORD: grimoire
            ME_CONFIG_MONGODB_URL: mongodb://grimoire:grimoire@mongodb:27017/

networks:
    net-grim: