name: Build & Publish
on: push

jobs:
   build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.x

   publish:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Docker Login      
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
                
    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with: 
        pull: true
        context: .
        push: true
        tags: |
          yucked/grimoire:latest
          yucked/grimoire:${{ github.run_number }}   
